version: '3.4'

services:
  #backend:
  #  image: ${DOCKER_REGISTRY-}backend
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  db:
    container_name: "db_container"
    image: postgres:15
    #restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
